# for getting chainlink data feeds:
dependencies:
# - <organization/repo>@<version>
#taken from: https://github.com/smartcontractkit/chainlink-brownie-contracts
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
#now everything from github repo contract section is available for brownie to use

#need to tell compiler what '@chainlink...' in contract actually means:
compiler:
  solc:
    remappings:
      - '@chainlink = smartcontractkit/chainlink-brownie-contracts@1.1.1'
      # seems ^ didnt really work - just copied full path into script

dotenv: .env
networks:
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e' # address of rinkeby chainlink eth price feed'
  #kovan: #can insert price feed addresses here for other networks
  #mainnet:
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development: 
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}

